---
abstract: 'a tool to store articles and publish them as eBooks to read later'
author:
  - 'Rupert Lane <rupert@rupert-lane.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::DBIx::Class::Schema: 0
  Test::More: 0
  Test::Most: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Zapzi
no_index:
  directory:
    - t
    - t/lib
    - xt
requires:
  Carp: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  DateTime::Format::SQLite: 0
  EBook::MOBI: 0
  Encode: 0
  Exporter: 0
  File::HomeDir: 0
  File::MMagic: 0
  Getopt::Lucid: 0
  HTML::Element: 0
  HTML::Entities: 0
  HTML::ExtractMain: 0
  HTTP::CookieJar: 0
  HTTP::Tiny: 0
  Moo: 0
  SQL::Translator: 0
  Text::Markdown: 0
  base: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/rupertl/app-zapzi/issues
  homepage: https://metacpan.org/release/App-Zapzi
  repository: git://github.com/rupertl/app-zapzi.git
version: 0.003
